### ISSUE TITLE
output is wrong for knowledge refresh in app editor

### ISSUE THREAD

**Issue by lukemarsden** [helixml/helix#599]
when setting knowledge refresh to hourly, the app editor spits out this config:

```
apiVersion: app.aispec.org/v1alpha1
kind: AIApp
metadata:
  name: Printer guide
spec:
  assistants:
    - model: llama3.1:8b-instruct-q8_0
      type: text
      knowledge:
        - name: https://www.connection.com/content/buying-guide/printer
          rag_settings:
            threshold: 0
            results_count: 0
            chunk_size: 0
            chunk_overflow: 0
            disable_chunking: false
            disable_downloading: false
          source:
            web:
              urls:
                - https://www.connection.com/content/buying-guide/printer
              crawler:
                enabled: true
                max_depth: 1
                max_pages: 1
                readability: true
          refresh_enabled: false
          refresh_schedule: "@hourly"
```
But that looks wrong that refresh_enabled is false while refresh_schedule is hourly.
